//
// Created by benno on 12.08.2020.
//

#ifndef CLION_DIRECTORIES_H
#define CLION_DIRECTORIES_H

#define RESOURCE_DIRECTORY "../res/"
#define SHADER_DIRECTORY RESOURCE_DIRECTORY"shaders/"
#define MODEL_DIRECTORY RESOURCE_DIRECTORY"models/"
#define TEXTURE_DIRECTORY RESOURCE_DIRECTORY"textures/"
#define FONT_DIRECTORY RESOURCE_DIRECTORY"fonts/"

#endif //CLION_DIRECTORIES_H
